# PyTorch Tutorial: Part 1
This notebook is a dedicated notebook for the exercises in the pytorch tutorial.

This is mainly a tutorial built using python extensions and is a test run for using exercises extension

---
#### Importing the Libraries

In [1]:
from __future__ import print_function
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

---
## What is PyTorch
PyTorch is scientific computing package for two sets of audiences
* A replacement for NumPy to use GPUs
* A deep learning research platform that gives a lot of flexibility and speed

### Tensors
Tensors are similar to NumPy ndarray and can be used with GPU

**Exercise 1: Create a 5 x 3 matrix, uninitialized:**

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.3224e+00, 6.7963e-43, 5.3224e+00],
        [6.7963e-43, 5.3204e+00, 6.7963e-43],
        [5.3204e+00, 6.7963e-43, 5.3215e+00],
        [6.7963e-43, 5.3215e+00, 6.7963e-43],
        [5.3214e+00, 6.7963e-43, 5.3214e+00]])


**Exercise 2: Construct a randomly initialized matrix:**

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[5.9977e-01, 5.2498e-01, 7.4775e-01],
        [9.7654e-01, 7.5698e-01, 1.9806e-01],
        [5.2957e-01, 6.1088e-01, 2.6518e-01],
        [6.3955e-01, 2.2835e-04, 2.9151e-01],
        [1.1270e-01, 8.3394e-01, 4.3582e-01]])


**Exercise 3: Construct a matrix filled with zeros and dtype long:**

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**Exercise 4: Construct a tensor with data values 5.5 and 3:**

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Can create tensors based on existing tensors oand reuse properties of input tensors. Can also override the dtype and add new values to tensors

**Exercise 5: Create a 5 x 3 matrix filled with ones with dtype double. Then create another matrix using the previous matrix filling it with random variables with dtype float:**

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.8978, -0.7646,  0.9634],
        [ 0.4594, -1.8857, -0.4459],
        [-0.1668,  2.4333, -0.2877],
        [-0.4043, -0.4938,  1.6049],
        [ 1.7206,  0.7524, -0.8522]])


**Exercise 6: Get the size of the matrix created before**

In [7]:
print(x.size())

torch.Size([5, 3])


---
## Operations
There are multiple syntaxes for operations, for example the addition operation

**Exercise 1: Create a matrix y filled with random variables and add with the x matrix from the previous section**

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.7120, -0.5110,  1.4878],
        [ 1.2188, -1.0855,  0.3307],
        [ 0.5730,  2.5398,  0.4156],
        [ 0.0946,  0.2667,  1.8452],
        [ 2.4197,  1.5582, -0.2113]])


**Exercise 2: Use alternative syntax for addition**

In [9]:
print(torch.add(x, y))

tensor([[ 2.7120, -0.5110,  1.4878],
        [ 1.2188, -1.0855,  0.3307],
        [ 0.5730,  2.5398,  0.4156],
        [ 0.0946,  0.2667,  1.8452],
        [ 2.4197,  1.5582, -0.2113]])


**Exercise 3: Create an empty result tensor and impute the output of adding tensors x and y into the result matrix**

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.7120, -0.5110,  1.4878],
        [ 1.2188, -1.0855,  0.3307],
        [ 0.5730,  2.5398,  0.4156],
        [ 0.0946,  0.2667,  1.8452],
        [ 2.4197,  1.5582, -0.2113]])


**Exercise 4: Add in-place x to y**

In [11]:
y.add(x)
print(y)

tensor([[0.8142, 0.2536, 0.5244],
        [0.7594, 0.8003, 0.7765],
        [0.7397, 0.1065, 0.7033],
        [0.4989, 0.7606, 0.2403],
        [0.6991, 0.8058, 0.6409]])


**Exercise 5: Use NumPy-like indexing to pull out the second column of tensor x**

In [12]:
print(x[:,1])

tensor([-0.7646, -1.8857,  2.4333, -0.4938,  0.7524])


Reshape and resize tensor using torch.view

**Exercise 6: Create tensor x of shape 4 x 4 with random numbers, create y tensor by reshaping x into a tensor of shape 16, create z tensor by reshaping x into tensor of shape -1 x 8**

Print the tensor sizes

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Exercise 7: Get the values from the tensor as python numbers using .item()**

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0378])
1.0377522706985474


## Converting Torch Tensor and Numpy Array

**Exercise 1: Convert a tensor into a NumPy array**

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


**Exercise 2: Convert a NumPy Array of ones into a Torch Tensor and add 1 to both**

In [17]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

**Exercise 1: Run the cell if CUDA is available using torch.device to move tensor into GPU**

In [20]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))