# PyTorch Tutorial
This notebook is a dedicated notebook for the exercises in the pytorch tutorial.

This is mainly a tutorial built using python extensions and is a test run for using exercises extension

---
#### Importing the Libraries

In [1]:
from __future__ import print_function
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot

%matplotlib inline

---
## What is PyTorch
PyTorch is scientific computing package for two sets of audiences
* A replacement for NumPy to use GPUs
* A deep learning research platform that gives a lot of flexibility and speed

### Tensors
Tensors are similar to NumPy ndarray and can be used with GPU

Exercise 1: Create a 5 x 3 matrix, uninitialized:

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.0653e-38],
        [1.0561e-38, 1.0102e-38, 6.2449e-39],
        [9.0919e-39, 1.0010e-38, 1.0102e-38],
        [1.0561e-38, 3.0307e-39, 7.3470e-39],
        [1.0194e-38, 1.0469e-38, 1.0010e-38]])


Exercise 2: Construct a randomly initialized matrix:

In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0090, 0.9665, 0.4311],
        [0.3549, 0.1467, 0.9643],
        [0.2732, 0.3097, 0.8826],
        [0.3345, 0.1954, 0.2870],
        [0.9541, 0.9384, 0.2445]])


Exercise 3: Construct a matrix filled with zeros and dtype long:

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Exercise 4: Construct a tensor directly from data:

In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Can create tensors based on existing tensors oand reuse properties of input tensors. Can also override the dtype and add new values to tensors

Exercise 5: Create a 5 x 3 matrix filled with ones with dtype double. Then create another matrix using the previous matrix filling it with random variables with dtype float:

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6173, -0.7469,  0.0486],
        [-0.4032, -0.9431, -1.7057],
        [-0.1874, -1.9286,  0.4901],
        [ 0.0171, -0.1028, -0.3909],
        [ 1.3627,  1.4554, -1.1131]])


Exercise 6: Get the size of the matrix created before

In [10]:
print(x.size())

torch.Size([5, 3])


---
## Operations
There are multiple syntaxes for operations, for example the addition operation

Exercise 1: Create a matrix y filled with random variables and add with the x matrix from the previous section


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0748, -0.4435,  0.5815],
        [ 0.5209, -0.8138, -1.0494],
        [ 0.0222, -1.8269,  0.9080],
        [ 0.1505,  0.6923,  0.5685],
        [ 1.9452,  2.3787, -0.3505]])


Exercise 2: Use alternative syntax for addition 

In [12]:
print(torch.add(x, y))

tensor([[ 0.0748, -0.4435,  0.5815],
        [ 0.5209, -0.8138, -1.0494],
        [ 0.0222, -1.8269,  0.9080],
        [ 0.1505,  0.6923,  0.5685],
        [ 1.9452,  2.3787, -0.3505]])


Exercise 3: Create an empty result tensor and impute the output of adding tensors x and y into the result matrix

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0748, -0.4435,  0.5815],
        [ 0.5209, -0.8138, -1.0494],
        [ 0.0222, -1.8269,  0.9080],
        [ 0.1505,  0.6923,  0.5685],
        [ 1.9452,  2.3787, -0.3505]])


Exercise 4: Add in-place x to y

In [14]:
y.add(x)
print(y)

tensor([[0.6921, 0.3034, 0.5330],
        [0.9240, 0.1293, 0.6563],
        [0.2096, 0.1017, 0.4179],
        [0.1334, 0.7951, 0.9594],
        [0.5825, 0.9234, 0.7626]])


Exercise 5: Use NumPy-like indexing to pull out the second column of tensor x

In [15]:
print(x[:,1])

tensor([-0.7469, -0.9431, -1.9286, -0.1028,  1.4554])


Reshape and resize tensor using torch.view

Exercise 6: Create tensor x of shape 4 x 4 with random numbers, create y tensor by reshaping x into a tensor of shape 16, create z tensor by reshaping x into tensor of shape -1 x 8

Print the tensor sizes

In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
