# PyTorch Tutorial: Part 2
This notebook is a dedicated notebook for the exercises in the pytorch tutorial.

This is mainly a tutorial built using python extensions and is a test run for using exercises extension

---
## Autograd: Automatic Differentiation

The autograd package gives automatic differentation for all operations on Tensors.Backpropogation is defines by how code is run and every iteration can be different

### Tensors
`torch.Tensor` is central class to the package and if set attribute `.requires.grad` as `True` all operations will be tracked on it. `.backward()`

To stop tracking use `.detach()` which will detach from all computation history and tracking future computations

TO prevent whole code block from getting tracked (use memory) wrap the block with `torch.no_grad():`. This is helpful for evaluating models that have trainable parameters with `requires_grad=True` but we don't need gradients.

One class that us important for autograd implementation -a `Function`

`Tensor` and `Function` interconnected to build acylic graph that encodes complete computation history. Each tensor has `.grad_fn` that references a `Function` that created the `Tensor` (except when user makes it where `grad_fn is None`)

To compute derivative you can call `.backward()` on `Tensor`. If it is a scalar (hold one element data), you don't need to specify any arguments to `.backward()`. If more elements specify `gradient` argument of matching shape

### Importing the libraries:

In [1]:
from __future__ import print_function
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

**Exercise 1: Create a tensor and set `requires_grad=True` to track computations**

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


**Exercise 2: Do a tensor operation**

In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


**Exercise 3: y was created as a result of the operation, so it has a `grad_fn`. Print out y grad_fn.**

In [4]:
print(y.grad_fn)

**Exercise 4: Create variable `z` by multiplying y by itself and by 3. Create another variable `out` which is the mean of `z`. Print out both `z` and `out`**

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


**Exercise 5: Create variable `a` that is a random 2x2 tensor. Next divide the product of a*3 by a-1. Print whether `a` `requires_grad`. Then set `a` to `requires_grad` and check if it does `requires_grad`. Next, create variable `b` that gets the sum of `a` multiplied by itself and check the `grad_fn`**

`requires_grad_(...)` changes an existing Tensor `requires_grad` flag in-place. The input defaults to `False` if not given.

In [6]:
a = torch.randn(2, 2)
a = ((a * 3)/(a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


---
## Gradients

Backgrpopogation now. Because `out` is a single scalar, `out.backward()` is the same as `out.backward(torch.tensor(1,))`

**Exercise 1: do `out` `.backward()` then print gradients d(out)/dx**

In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


**Exercise 2: **

**Exercise 3: **

**Exercise 4: **

**Exercise 5: **

**Exercise 6: **