# PyTorch Tutorial
This notebook is a dedicated notebook for the exercises in the pytorch tutorial.

This is mainly a tutorial built using python extensions and is a test run for using exercises extension

---
#### Importing the Libraries

In [1]:
from __future__ import print_function
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot

%matplotlib inline

---
## What is PyTorch
PyTorch is scientific computing package for two sets of audiences
* A replacement for NumPy to use GPUs
* A deep learning research platform that gives a lot of flexibility and speed

### Tensors
Tensors are similar to NumPy ndarray and can be used with GPU

Exercise 1: Create a 5 x 3 matrix, uninitialized:

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.0653e-38],
        [1.0561e-38, 1.0102e-38, 6.2449e-39],
        [9.0919e-39, 1.0010e-38, 1.0102e-38],
        [1.0561e-38, 3.0307e-39, 7.3470e-39],
        [1.0194e-38, 1.0469e-38, 1.0010e-38]])


Exercise 2: Construct a randomly initialized matrix:

In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0090, 0.9665, 0.4311],
        [0.3549, 0.1467, 0.9643],
        [0.2732, 0.3097, 0.8826],
        [0.3345, 0.1954, 0.2870],
        [0.9541, 0.9384, 0.2445]])


Exercise 3: Construct a matrix filled with zeros and dtype long:

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Exercise 4: Construct a tensor directly from data:

In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])
